apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
  # Namespace depends on the configuration in the storageclass.yaml
  namespace: kube-system
stringData:
  accessKeyID: minio
  secretAccessKey: minio123
  # For AWS set it to "https://s3.<region>.amazonaws.com"
  endpoint: http://192.168.49.2:9000
  # If not on S3, set it to ""
  region: ""